# Generated by Django 3.1.2 on 2020-11-16 11:07

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, max_length=512)),
                ('isbn10', models.CharField(blank=True, max_length=10)),
                ('isbn13', models.CharField(blank=True, max_length=13)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(max_length=256, upload_to='Books/', validators=[books.validators.validate_pdf])),
            ],
        ),
    ]
